services:
  crawl:
    container_name: crawl
    build: .
    ports:
      - "9080:9080"
    volumes:
      - ./crawl:/scrapyrt/project
    depends_on:
      - splash
    networks:
      - search-network
  
  fastapi:
    container_name: api_core_search_gg
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - "8001:8000"
    depends_on:
      - crawl
    networks:
      - search-network
  splash:
    container_name: splash
    image: scrapinghub/splash
    ports:
      - "8050:8050"
    networks:
      - search-network

networks:
  search-network:
    external: true